[package]
name = "rust" #v-1.43.0
version = "0.0.1"
authors = ["Nikunj Kumar Nakum"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
